DELETE FROM Test_Result
DELETE FROM Test_QTG
DELETE FROM "Statistics"
DELETE FROM Simulator_State
DELETE FROM Simulator_Session
DELETE FROM Predefined_Session
DELETE FROM Session_Category
DELETE FROM RecoveryAction
DELETE FROM MalfunctionDevice
DELETE FROM Malfunction
DELETE FROM Maintenance
DELETE FROM Maintenance_Type
DELETE FROM Inspection
DELETE FROM UserRole
DELETE FROM "Role"
DELETE FROM "User"
DELETE FROM Inspection_Type
DELETE FROM Device